version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - conftest
  - docstrings
  - healthcheck
  - homelab
  - httponly
  - logformat
  - setex
  - Taskfile
  - unsign
  - websecure
  - wsgi
  - containo
ignoreWords: []
import: []
