# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json
http:
  router:
    # Homelab Web server on labs domain - requires authentication
    r-homelab-web:
      rule: "Host(`web.labs.home.arpa`)"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      service: sv-homelab-web
      middlewares:
        - auth-check

    # Homelab Web server on sslip domain - requires authentication
    r-homelab-web-sslip:
      rule: "Host(`web-10-9-8-177.sslip.io`)"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      service: sv-homelab-web
      middlewares:
        - auth-check

    # Homelab Auth server on labs domain
    r-homelab-auth:
      rule: "Host(`auth.labs.home.arpa`)"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      service: sv-homelab-auth
      middlewares: []

    # Homelab Auth server on sslip domain
    r-homelab-auth-sslip:
      rule: "Host(`auth-10-9-8-177.sslip.io`)"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      service: sv-homelab-auth
      middlewares: []


  middlewares:
    # ForwardAuth-only check.
    # The /validate handler returns:
    # - 200 when authenticated
    # - 307 + Location when unauthenticated
    auth-check:
      forwardAuth:
        address: "http://127.0.0.1:55000/validate"
        trustForwardHeader: true
        preserveLocationHeader: true
        authResponseHeaders:
          - "Set-Cookie"
        addAuthCookiesToResponse:
          - "pecan_sandy" # needs to match config.yaml:cookie.name


  services:
    sv-homelab-auth:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:55000"
        healthCheck:
          path: "/healthz"

    sv-homelab-web:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8000"
        healthCheck:
          path: "/healthz"
